version: '3.3'

volumes:
  foodgram_pg_data:
  foodgram_static:
  foodgram_media:

services:

  db:
    image: postgres:13.0-alpine
    volumes:
      - foodgram_pg_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    restart: always
  
  backend:
    build: ./backend/
    container_name: foodgram_backend
    restart: always
    env_file:
      - ./.env
    volumes:
      - foodgram_static:/app/static/
      - foodgram_media:/app/media/
    depends_on:
      - db

  frontend:
    image: alexkyzmin/foodgram_frontend:latest
    container_name: foodgram_frontend
    volumes:
      - ../frontend/:/app/result_build/
  
  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - foodgram_static:/var/html/static/
      - foodgram_media:/var/html/media/
    depends_on:
      - frontend
    restart: always
